---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(viridis)
```

```{r}
data(nyc_airbnb)

nyc_airbnb =
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(borough = neighbourhood_group) |> 
  select(borough, neighbourhood, stars, price, room_type, lat, long) |> 
  drop_na(stars)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
boroughs = nyc_airbnb |> 
  distinct(borough) |> 
  pull()

selectInput(
  "borough_choice", 
  label = h3("Select borough"),
  choices = boroughs, selected = "Manhattan")
```

```{r}
max_price = 1000
min_price = nyc_airbnb |> distinct(price) |> min()

sliderInput(
  "price_range", 
  label = h3("Choose price range"), 
  min = min_price, max = max_price, value = c(100, 400))
```

```{r}
room_choice = 
  nyc_airbnb |> 
  distinct(room_type) |> 
  pull()

radioButtons(
  "room_choice", 
  label = h3("Choose room type"),
  choices = room_choice, selected = "Entire home/apt")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({ 
  nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) |> 
  plot_ly(
    x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
    alpha = 0.5, color = ~price, text = ~text_label)
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
  nyc_airbnb |>
  filter(
    borough == input[["borough_choice"]], 
    price %in% input[["price_range"]][1]:input[["price_range"]][2],
    room_type == input[["room_choice"]]) |>
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) |> 
  plot_ly(
    x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
    alpha = 0.5, color = ~price, text = ~text_label)
})
```

### Chart C

```{r}
renderPlotly({ 
  common_neighborhoods =
    nyc_airbnb |> 
    filter(
      borough == input[["borough_choice"]],
      price %in% input[["price_range"]][1]:input[["price_range"]][2],
      room_type == input[["room_choice"]]) |>
    count(neighbourhood, sort = TRUE) |> 
    top_n(8) |> 
    select(neighbourhood)

  nyc_airbnb |>
    filter(
      borough == input[["borough_choice"]],
      price %in% input[["price_range"]][1]:input[["price_range"]][2],
      room_type == input[["room_choice"]]) |>
    inner_join(., common_neighborhoods, by = "neighbourhood") |> 
    plot_ly(y = ~price, color = ~neighbourhood, type = "box")
})
```

